"""initial schema - 18 tablas

Revision ID: 1b719f78cc1b
Revises: 
Create Date: 2026-03-08 18:11:15.469153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b719f78cc1b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('careers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('area', sa.String(length=255), nullable=False),
    sa.Column('holland_codes', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('salary_range', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('employability', sa.Float(), nullable=False),
    sa.Column('saturation_index', sa.Float(), nullable=False),
    sa.Column('mineduc_data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_careers_area'), 'careers', ['area'], unique=False)
    op.create_table('games',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('skills_evaluated', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='game_difficulty', create_constraint=True), nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_slug'), 'games', ['slug'], unique=True)
    op.create_table('institutions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('google_workspace_config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('plan', sa.Enum('FREE', 'BASIC', 'PREMIUM', name='institution_plan', create_constraint=True), nullable=False),
    sa.Column('max_students', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutions_slug'), 'institutions', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('role', sa.Enum('ESTUDIANTE', 'APODERADO', 'ORIENTADOR', 'ADMIN_COLEGIO', 'SUPER_ADMIN', name='user_role', create_constraint=True), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_institution_id'), 'users', ['institution_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_institution_id'), 'audit_logs', ['institution_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('career_simulations',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('career_id', sa.UUID(), nullable=False),
    sa.Column('simulation_data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_narrative', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_simulations_career_id'), 'career_simulations', ['career_id'], unique=False)
    op.create_index(op.f('ix_career_simulations_student_id'), 'career_simulations', ['student_id'], unique=False)
    op.create_table('consent_records',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=False),
    sa.Column('consent_type', sa.Enum('RECORDING', 'AI_PROCESSING', 'DATA_STORAGE', name='consent_type', create_constraint=True), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('method', sa.Enum('DIGITAL', 'PHYSICAL', name='consent_method', create_constraint=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_granted_by'), 'consent_records', ['granted_by'], unique=False)
    op.create_index(op.f('ix_consent_records_student_id'), 'consent_records', ['student_id'], unique=False)
    op.create_table('game_results',
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('metrics', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('skills_scores', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_results_game_id'), 'game_results', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_results_institution_id'), 'game_results', ['institution_id'], unique=False)
    op.create_index(op.f('ix_game_results_student_id'), 'game_results', ['student_id'], unique=False)
    op.create_table('parent_student_links',
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_student_links_parent_id'), 'parent_student_links', ['parent_id'], unique=False)
    op.create_index(op.f('ix_parent_student_links_student_id'), 'parent_student_links', ['student_id'], unique=False)
    op.create_table('sessions',
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('orientador_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='session_status', create_constraint=True), nullable=False),
    sa.Column('google_calendar_event_id', sa.String(length=255), nullable=True),
    sa.Column('google_meet_link', sa.String(length=512), nullable=True),
    sa.Column('notes_by_student', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['orientador_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_institution_id'), 'sessions', ['institution_id'], unique=False)
    op.create_index(op.f('ix_sessions_orientador_id'), 'sessions', ['orientador_id'], unique=False)
    op.create_index(op.f('ix_sessions_student_id'), 'sessions', ['student_id'], unique=False)
    op.create_table('student_longitudinal_profiles',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('skills', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('interests', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('learning_patterns', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('happiness_indicators', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('career_recommendations', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('riasec_history', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('data_sources', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_longitudinal_profiles_institution_id'), 'student_longitudinal_profiles', ['institution_id'], unique=False)
    op.create_index(op.f('ix_student_longitudinal_profiles_student_id'), 'student_longitudinal_profiles', ['student_id'], unique=True)
    op.create_table('test_results',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('test_type', sa.String(length=100), nullable=False),
    sa.Column('answers', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('scores', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('result_code', sa.String(length=50), nullable=True),
    sa.Column('certainty', sa.Float(), nullable=True),
    sa.Column('test_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_results_institution_id'), 'test_results', ['institution_id'], unique=False)
    op.create_index(op.f('ix_test_results_user_id'), 'test_results', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('additional_info', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('adaptive_questionnaires',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('questions', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('answers', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('evaluation', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'EXPIRED', name='adaptive_questionnaire_status', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adaptive_questionnaires_session_id'), 'adaptive_questionnaires', ['session_id'], unique=False)
    op.create_index(op.f('ix_adaptive_questionnaires_student_id'), 'adaptive_questionnaires', ['student_id'], unique=False)
    op.create_table('ai_usage_logs',
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('pipeline_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('model_requested', sa.String(length=100), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('validation_retries', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_logs_institution_id'), 'ai_usage_logs', ['institution_id'], unique=False)
    op.create_index(op.f('ix_ai_usage_logs_pipeline_name'), 'ai_usage_logs', ['pipeline_name'], unique=False)
    op.create_index(op.f('ix_ai_usage_logs_session_id'), 'ai_usage_logs', ['session_id'], unique=False)
    op.create_table('session_ai_analyses',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('interests_detected', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('skills_detected', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('emotional_sentiment', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('suggested_tests', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('suggested_games', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('processing_time_seconds', sa.Float(), nullable=False),
    sa.Column('reviewed_by_orientador', sa.Boolean(), nullable=False),
    sa.Column('orientador_edits', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_ai_analyses_session_id'), 'session_ai_analyses', ['session_id'], unique=True)
    op.create_table('session_recordings',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('google_drive_file_id', sa.String(length=255), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_url', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'DOWNLOADING', 'DOWNLOADED', 'DELETED', name='recording_status', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_recordings_session_id'), 'session_recordings', ['session_id'], unique=True)
    op.create_table('session_transcripts',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('google_docs_id', sa.String(length=255), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('segments', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('GOOGLE_MEET_AUTO', 'MANUAL', 'WHISPER', name='transcript_source', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_transcripts_session_id'), 'session_transcripts', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_transcripts_session_id'), table_name='session_transcripts')
    op.drop_table('session_transcripts')
    op.drop_index(op.f('ix_session_recordings_session_id'), table_name='session_recordings')
    op.drop_table('session_recordings')
    op.drop_index(op.f('ix_session_ai_analyses_session_id'), table_name='session_ai_analyses')
    op.drop_table('session_ai_analyses')
    op.drop_index(op.f('ix_ai_usage_logs_session_id'), table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_logs_pipeline_name'), table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_logs_institution_id'), table_name='ai_usage_logs')
    op.drop_table('ai_usage_logs')
    op.drop_index(op.f('ix_adaptive_questionnaires_student_id'), table_name='adaptive_questionnaires')
    op.drop_index(op.f('ix_adaptive_questionnaires_session_id'), table_name='adaptive_questionnaires')
    op.drop_table('adaptive_questionnaires')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_test_results_user_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_institution_id'), table_name='test_results')
    op.drop_table('test_results')
    op.drop_index(op.f('ix_student_longitudinal_profiles_student_id'), table_name='student_longitudinal_profiles')
    op.drop_index(op.f('ix_student_longitudinal_profiles_institution_id'), table_name='student_longitudinal_profiles')
    op.drop_table('student_longitudinal_profiles')
    op.drop_index(op.f('ix_sessions_student_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_orientador_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_institution_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_parent_student_links_student_id'), table_name='parent_student_links')
    op.drop_index(op.f('ix_parent_student_links_parent_id'), table_name='parent_student_links')
    op.drop_table('parent_student_links')
    op.drop_index(op.f('ix_game_results_student_id'), table_name='game_results')
    op.drop_index(op.f('ix_game_results_institution_id'), table_name='game_results')
    op.drop_index(op.f('ix_game_results_game_id'), table_name='game_results')
    op.drop_table('game_results')
    op.drop_index(op.f('ix_consent_records_student_id'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_granted_by'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_career_simulations_student_id'), table_name='career_simulations')
    op.drop_index(op.f('ix_career_simulations_career_id'), table_name='career_simulations')
    op.drop_table('career_simulations')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_institution_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_institution_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_institutions_slug'), table_name='institutions')
    op.drop_table('institutions')
    op.drop_index(op.f('ix_games_slug'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_careers_area'), table_name='careers')
    op.drop_table('careers')
    # ### end Alembic commands ###
